//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINSAL
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:interfaceliswebservice", ConfigurationName="MINSAL.interfacelisPortType")]
    public interface interfacelisPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:interfacelis#acceptMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<MINSAL.acceptMessageResponse> acceptMessageAsync(MINSAL.acceptMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:interfacelis#checkin", ReplyAction="*")]
        System.Threading.Tasks.Task<MINSAL.checkinResponse> checkinAsync(MINSAL.checkinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:interfacelis#checkout", ReplyAction="*")]
        System.Threading.Tasks.Task<MINSAL.checkoutResponse> checkoutAsync(MINSAL.checkoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:interfacelis#generarMensajeSolicitud", ReplyAction="*")]
        System.Threading.Tasks.Task<MINSAL.generarMensajeSolicitudResponse> generarMensajeSolicitudAsync(MINSAL.generarMensajeSolicitudRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="acceptMessage", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class acceptMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string json_array;
        
        public acceptMessageRequest()
        {
        }
        
        public acceptMessageRequest(string json_array)
        {
            this.json_array = json_array;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="acceptMessageResponse", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class acceptMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public acceptMessageResponse()
        {
        }
        
        public acceptMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkin", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class checkinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string json_array;
        
        public checkinRequest()
        {
        }
        
        public checkinRequest(string json_array)
        {
            this.json_array = json_array;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkinResponse", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class checkinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public checkinResponse()
        {
        }
        
        public checkinResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkout", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class checkoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string guid;
        
        public checkoutRequest()
        {
        }
        
        public checkoutRequest(string guid)
        {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkoutResponse", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class checkoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public checkoutResponse()
        {
        }
        
        public checkoutResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarMensajeSolicitud", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class generarMensajeSolicitudRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param;
        
        public generarMensajeSolicitudRequest()
        {
        }
        
        public generarMensajeSolicitudRequest(string param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarMensajeSolicitudResponse", WrapperNamespace="urn:interfacelis", IsWrapped=true)]
    public partial class generarMensajeSolicitudResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public generarMensajeSolicitudResponse()
        {
        }
        
        public generarMensajeSolicitudResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface interfacelisPortTypeChannel : MINSAL.interfacelisPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class interfacelisPortTypeClient : System.ServiceModel.ClientBase<MINSAL.interfacelisPortType>, MINSAL.interfacelisPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public interfacelisPortTypeClient() : 
                base(interfacelisPortTypeClient.GetDefaultBinding(), interfacelisPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.interfacelisPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public interfacelisPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(interfacelisPortTypeClient.GetBindingForEndpoint(endpointConfiguration), interfacelisPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public interfacelisPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(interfacelisPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public interfacelisPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(interfacelisPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public interfacelisPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MINSAL.acceptMessageResponse> MINSAL.interfacelisPortType.acceptMessageAsync(MINSAL.acceptMessageRequest request)
        {
            return base.Channel.acceptMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MINSAL.acceptMessageResponse> acceptMessageAsync(string json_array)
        {
            MINSAL.acceptMessageRequest inValue = new MINSAL.acceptMessageRequest();
            inValue.json_array = json_array;
            return ((MINSAL.interfacelisPortType)(this)).acceptMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MINSAL.checkinResponse> MINSAL.interfacelisPortType.checkinAsync(MINSAL.checkinRequest request)
        {
            return base.Channel.checkinAsync(request);
        }
        
        public System.Threading.Tasks.Task<MINSAL.checkinResponse> checkinAsync(string json_array)
        {
            MINSAL.checkinRequest inValue = new MINSAL.checkinRequest();
            inValue.json_array = json_array;
            return ((MINSAL.interfacelisPortType)(this)).checkinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MINSAL.checkoutResponse> MINSAL.interfacelisPortType.checkoutAsync(MINSAL.checkoutRequest request)
        {
            return base.Channel.checkoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<MINSAL.checkoutResponse> checkoutAsync(string guid)
        {
            MINSAL.checkoutRequest inValue = new MINSAL.checkoutRequest();
            inValue.guid = guid;
            return ((MINSAL.interfacelisPortType)(this)).checkoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MINSAL.generarMensajeSolicitudResponse> MINSAL.interfacelisPortType.generarMensajeSolicitudAsync(MINSAL.generarMensajeSolicitudRequest request)
        {
            return base.Channel.generarMensajeSolicitudAsync(request);
        }
        
        public System.Threading.Tasks.Task<MINSAL.generarMensajeSolicitudResponse> generarMensajeSolicitudAsync(string param)
        {
            MINSAL.generarMensajeSolicitudRequest inValue = new MINSAL.generarMensajeSolicitudRequest();
            inValue.param = param;
            return ((MINSAL.interfacelisPortType)(this)).generarMensajeSolicitudAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.interfacelisPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.interfacelisPort))
            {
                return new System.ServiceModel.EndpointAddress("urn:interfaceliswebservice");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return interfacelisPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.interfacelisPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return interfacelisPortTypeClient.GetEndpointAddress(EndpointConfiguration.interfacelisPort);
        }
        
        public enum EndpointConfiguration
        {
            
            interfacelisPort,
        }
    }
}
